#!/bin/sh

MODDIR="/lib/modules/$(uname -r)/updates"

case "$1" in
    start)
         echo "scull_load and misc modules"
         cd "$MODDIR" && /usr/bin/scull_load
         cd "$MODDIR" && /usr/bin/module_load faulty
         modprobe hello
         ;;
    stop)
         echo "scull_unload and misc modules"
         cd "$MODDIR" && /usr/bin/scull_unload
         cd "$MODDIR" && /usr/bin/module_unload faulty
         rmmod hello
         ;;
    *)

         echo "Usage: $0 {start|stop}"
         exit 1

esac

exit 0
